# config.yaml

data:
  # 调整路径以匹配你的文件位置
  adj_path: "data/adj_METR-LA.pkl"
  sensor_data_path: "data/METR-LA.h5"
  num_nodes: 207  # METR-LA 数据集的节点数
  
  # 数据集划分比例
  train_split: 0.7
  val_split: 0.1
  # 测试集比例将是 1 - train_split - val_split

model:
  type: "DCRNN"
  # 注意: 如果你做了特征工程, in_features可能需要修改
  # 例如: 速度 + 一天中的时间 + 一周中的星期几 = 3
  in_features: 2
  out_features: 1     # 我们只预测速度
  num_layers: 2       # DCGRU堆叠的层数
  hidden_features: 64 # RNN隐藏层维度
  num_diffusion_steps: 2 # 扩散步数 K

train:
  epochs: 100
  batch_size: 64
  learning_rate: 0.001
  patience: 15        # 早停的耐心轮数
  seed: 42
  
  seq_len: 12         # 输入序列长度 (12 * 5分钟 = 1小时)
  horizon: 12         # 预测序列长度 (12 * 5分钟 = 1小时)

  teacher_forcing_ratio: 0.5
  grad_norm_clip: 5.0

  # --- 修改部分 ---
  # 移除了 resume_training: false
  # 只保留检查点文件的路径
  checkpoint_path: "checkpoints/latest_checkpoint.pth"

log:
  log_dir: "logs/"
  model_save_dir: "saved_models/"